export const donorList2025 = [
  'Pedro Domingos',
  'Mihaela Rosca',
  'YIFEI DAI',
  'Argmax, Inc.',
  'Yoshitomo Matsubara',
  'Greg Durrett',
  'Mona Diab',
  'Chih-Hao Fang',
  'Tim Genewein',
  'Niranjan Balasubramanian',
  'Antoine Ledent',
  'Fei Sha',
  'Maryam Fazel-Zarandi',
  'Razvan Pascanu',
  'Linhong Zhu',
  'Nasser Manesh',
  'Winston Chou',
  'JinYeong Bak',
  'Pradeep Dasigi',
  'Lihong Li',
  'Xueyan Zou',
  'Kunping Yang',
  'Shib Dasgupta',
  'Peter Railton',
  'Ermin Wei',
  'Chong Wang',
  'Daniel Soosai',
  'Vineet K',
  'Igor Gitman',
  'Liz Boschee',
  'Vignesh Kothapalli',
  'Juho Lee',
  'Timothy Nguyen',
  'Josh Roy',
  'Danilo Rezende',
  'Minoji Masataka',
  'Pavan Maddamsetti',
  'Marc Pavese',
  'The Fin AI',
  'Philipp Gysel',
  'Ryo Ueda',
  'Shuchang Zhou',
  'Gal Chechik',
  'Naoto Inoue',
  'Yusuke Oda',
  'XU Gang EIT',
  'Raviteja Vemulapalli',
  'Jason Riesa',
  'Disrupting SASU',
  'Dhruv Agarwal',
  'Well Wisher',
  'Niels Mündler',
  'Hui Yong Kim',
  'Caroline Wang',
  'Sharan Vaswani',
  'Hartwig Adam',
  'henry choi',
  'Edward Choi',
  'Yong Jae Lee',
  'Hongyin Luo',
  'Kota Yamaguchi',
  'Giles Hooker',
  'Masaaki Tsuchida',
  'Naoya Inoue',
  'Julia Kreutzer',
  'Sangdon Park',
  'Sejik Park',
  'Mitsu Ogihara',
  'Zeeshan Ahmed',
  'Rasit Eskicioglu',
  'Luis Oala',
  'Mark Daley',
  'Wee Hyong Tok',
  'Mark Nitzberg',
  'Panos Ipeirotis',
  'Martin Klissarov',
  'Diego de las Casas',
  'Sushant',
  'Pablo Samuel Castro',
  'Bosse Rüschmann',
  'Shaochen (Henry) Zhong',
  'Jonathan Scarlett',
  'Rahul G. Krishnan',
  'Atlas Wang',
  'Mengye Ren',
  'Philippe Beaudoin',
  'Yingzhen Li',
  'Abhishek Das',
  'Caner Hazirbas',
  'Muhammed Basil',
  'Muhammet Bastan',
  'Siba Smarak Panigrahi',
  'Susan Murphy',
  'Miquel Ramirez',
  'Liu Yang',
  'Despoina Magka',
  'Jun-Liang Lin',
  'Massimo Piccardi',
  'Charlotte Bunne',
  'Tuan Duong Trinh',
  'Gautam Mittal',
  'Jiwei Li',
  'Zaccharie Ramzi',
  'Stephen Zhou',
  'Giuseppe Attardi',
  'Andreas Rückle',
  'Xuanjie Liu',
  'Bridger Ammar',
  'Joseph Viviano',
  'Ting Hua',
  'Ankit Arun',
  'Sergio',
  'Jae Wook Song',
  'Alexandre Gramfort',
  'Kamal Premaratne',
  'fiora',
  'Abdallah Aaraba',
  'Yiming Huang',
  'Maria Korosteleva',
  'Bai Song',
  'Aitor García Pablos',
  'Marios Fournarakis',
  'Philip Brown',
  'Aqasch',
  'Johannes Rainer',
  'Qing Zhong',
  'Masayoshi MIZUNO',
  'Jing Xiong',
  'Kshitij Fadnis',
  'Hao Wang',
  'Wray Buntine',
  'Xiaolin Hu',
  'Dong-Hee Paek',
  'Alex Heyman',
  'John Harby',
  'AlexP',
  'Usashi',
  'David Banks',
  'Misha Glazunov',
  'Shuai Shao',
  'Junhwa Hur',
  'Stan Peshterliev',
  'Madhu Gopinathan',
  'Liu Yu',
  'Simon Bultmann',
  'Pradeep K Dubey',
  'Nan Wu',
  'Ben Evans',
  'Pavlo Vasylenko',
  'Jan Achterhold',
  'Odd Erik Gundersen',
  'Hongliang Liu',
  'Justin Deschenaux',
  'Jun-Cheng Chen',
  'Bruno Ribeiro',
  'Surbhi Goel',
  'Xinrun Wang',
  'Nandan Kumar Jha',
  'Constantine Lignos',
  'Arthur Zalevsky',
  'Kamal Maher',
  'Chaitat Utintu',
  'Nontawat Charoenphakdee',
  'Xiang Zhang',
  'Alex Dimakis',
  'Zhi Wen',
  'Nguyễn Tuấn Bình',
  'Shayaan Emran',
  'Shalmali Joshi',
  'Memming',
  'Sun Hanqing',
  'Boaz Carmeli',
  'Le Yang (XJTU)',
  'Kuan-Hao Huang',
  'Hadi Rad',
  'Samuel Stocksieker',
  'Sudhamshu Hosamane',
  'F Sh',
  'Asad Ullah Khan',
  'Keetofree',
  'Riccardo Taormina',
  'wang ning',
  'Trang Tran',
  'Siddhant (Sid) Bhambri',
  'Sergio Valcarcel Macua',
  'Ted Willke',
  'Sören Laue',
  'Vignesh Ganapathiraman',
  'Phillip Rhodes',
  'Pavel',
  'Sailik Sengupta',
  'Wei-Yin Ko',
  'Zhuohang Li',
  'laura palagi',
  'Daehee Lee',
  'Rajendra Boppana',
  'Arman Zharmagambetov',
  'Gabor Pituk',
  'Alexander Timans',
  'Seungtaek Choi',
  'Anton Zubekhin',
  'Xinyu Li',
  'Luis Javier Rodriguez-Fuentes',
  'Sam Thelin',
  'Xiao Shi',
  'Woongbae Jeon',
  'Pratik Mehta',
  'Suhang Wang',
  'Rujikorn Charakorn',
  'PNL',
  'Aditya Acharya',
  'pauek',
  'Mayank Daswani',
  'Haipeng Chen',
  'Yi Xie',
  'Mianchu Wang',
  'Farzin Haddadpour',
  'Qiao Gu',
  'Mihir Parmar',
  'Hosein Bar',
  'Arthur Gretton',
  '~Songtao_Liu2',
  'Peng Chen',
  'Vivek Pandit',
  'Ece Takmaz',
  'Ziyang Gong',
  'Qidong Liu',
  'Wenzhang Wei',
  'Cheng-You Lu',
  'Peter McCabe',
  'MY_Wang',
  'Daniel Felipe Ordoñez Apraez',
  'Navdeep',
  'Julius Aka',
  'Yuxuan Zhao',
  'Huaigang Huang',
  'Lars Rasmusson',
  'Tejwardhan Patil',
  'Leon Lang',
  'Yigit Ihlamur',
  'Mehrab Hamidi',
  'Lei GZU Zhang',
  'Sungjin Ahn',
  'Jung-Hun Shin',
  'Kunal Aneja',
  'Xiaoya Li',
  'Guangxing Liu',
  'Xiangru Jian',
  'Xinxi Zhang',
  'Rushikesh Zawar',
  'Alex Pierron',
  'Xiaojie Yang',
  'VICTOR RODRIGUEZ FERNANDEZ',
  'Federico Errica',
  'Mary Phuong',
  'Gal Michael Harari',
  'Can Rager',
  'Jin-Hwa Kim',
  'Shrinu',
  'Siyuan Yang',
  'Yucheng Guo',
  'Anh Nguyen',
  'Zhu Liu',
  'Kaikai Wei',
  'Minbeom Kim',
  'Abeer Sharma',
  'Qi Zhang (Temple University)',
  'Jonathon Schwartz',
  'Aristides Milios',
  'Arick Grootveld',
  'Chong Zhang (张冲)',
  'Shantanu Sharma',
  'Alexander Soare',
  'Damien Nouvel',
  'LIU Yiqian',
  'Pin-Yu Chen',
  'Shane Storks',
  'Leonard Papenmeier',
  'Kenta Matsui',
  'Urja Pawar',
  'lokinko',
  'Kutay Bölat',
  'Antonis Bikakis',
  'Yuanfu Sun',
  'M. X. L.',
  'Steven McDonagh',
  'Haozhe Tian',
  'Xianyuan Liu',
  'Anil Kumar Singh',
  'Xiaohang Yu',
  'Renzhe Xu',
  'Jaco',
  'Olga Slizovskaia',
  'Yitong Li',
  'Qilong Jia',
  'Harahan',
  'Tianjun Yao',
  'Davor Runje',
  'Soowoong Kim',
  'Abdisalam Mahamed Badel',
  'Clément Lalanne',
  'Yanan Sui',
  'Yen-Chang Hsu',
  'Chenwei Jin',
  'Dian JIN',
  'Jason Armitage',
  'Francesco De Santis',
  'Püren Güler',
  'Jas',
  'Changlun Li',
  'Jian Wang',
  'Deokhyung Kang',
  'Jingzhe Shi',
  'Xiao Yu',
  'BONGMO',
  'Zongmin',
  'Ashish',
  'Adrian R Pearce',
  'Ming Li',
  'Pruthwik Mishra',
  'Hyung-Seok Oh',
  'Yingqiang',
  'Yajun Yang',
  'Shi-ang Qi',
  'Chenyi Zhuang',
  'Xiaojun Wu',
  'Yupu Yao',
  'Lingyu Li',
  'Xiang Tong',
  'Rui Wang',
  'Ji Qi',
  'wyeh',
  'Zihua Si',
  'Da-Chen Lian',
  'Minghan Zhu',
  'Chong Wu',
  'Zhaolong Ling',
  'Xi Zhang',
  'Haihong Zhao',
  'Canzhe Zhao',
  'Sharif S M A',
  'Zihao Wei',
  'Zidong',
  'Kun Wang',
  'Hyunwoo Kim',
  'Jiahao Wang',
  'Xintong Li',
  'JJYDXFS',
  'Jiangjie Qiu',
  'Keon Lee',
  'Longyin Zhang',
  'Juyeon Heo',
  'Andrew Nedi',
  'Yicheng Luo',
  'Yiming Cui',
  'Anonymous',
  'Kentaro Fujii',
  'Xu Cao',
  'Xundong Wu',
  'Hsin-Min Lu',
  'Wang Weiwei',
  'Naoya Takeishi',
  'Siqi Shen',
  'Jinhao Liang',
  'Jeongwhan Choi',
  'Alisa Zhila',
  'Richard Zhuang',
  'Yue Yu',
  'Hazem El-Alfy',
  'Wenhao Ding',
  'Jiahe Li',
  'Momin Ahmad Khan',
  'Takahiro Maeda',
  'Dixi Yao (Uchicago)',
  'Ryan Thompson',
  'Ting Chen',
  'Soheil Kolouri',
  'Fali Wang',
  'Nan Jiang',
  'Pablo Rojas Sedó',
  'Martin Sundermeyer',
  'Zaigham Abbas Randhawa',
  'Vasily Ilin',
  'Zhanwen Chen',
  'Suryanarayana Sankagiri',
  'Zijun Wu',
  'Ajay Unagar',
  'Fujie Zhang',
  'Shohei Shimizu',
  'Guang Yang',
  'Changjiang Cai',
  'Marcus Klasson',
  'Xu Liu',
  'Johannes Mehrer',
  'Quanyi Li',
  'Linyi Li',
  'Kostis Gourgoulias',
  'Jongmin Mun',
  'Lance Legel',
  'Shuhong Zheng',
  'Morteza Karimzadeh',
  'Helen Zhang',
  'Yunhe',
  'Sasidharan Mahalingam',
  'Timothy Sum Hon Mun',
  'Can Chen',
  'Kaizhen Tan',
  'Samuel',
  'Simon DeDeo',
  'Sanket Gupta',
  'Xikun Zhang',
  'Benjamin Feuer',
  'Tianruo Zhang',
  'Yuhao Zhong',
  'Rubén Ballester',
  'Boris Defourny',
  'Roozbeh Mohit',
  'Chen-Hsuan Lin',
  'Alexander Chebykin',
  'Alexey Kurennoy',
  'Bishoy Galoaa',
  'Keisuke Onoue',
  'Leo Lahti',
  'Zhaokai Wang',
  'Yongjun He',
  'Jiahui Chen',
  'Chong Shen',
  'Chaosheng',
  'Yijia',
  'Ramazan Gokberk Cinbis',
  'Yash Sanjay Bhalgat',
  'Taewoon Kim',
  'Niclas Boehmer',
  'So Takao',
  'Amit Dhanda',
  'Wenhao Pan',
  'Ahmed Wali',
  'Shuyi Wang',
  'Saba Ghanbari Haez',
  'Zachary Chase',
  'Sylee Beltiukov',
  'Kefan Song',
  'Ge Shi',
  'BoQ',
  'Haodong',
  'Haodong Li',
  'Jenny Boavista',
  'Soubhik Sanyal',
  'Feng Dong',
  'Sarita Abraham',
  'Ali Modarressi',
  'Mohammad Reza Samsami',
  'Seongwoong Shim',
  'Jaeho Kim',
  'Chengsong',
  'Will Cai',
  'Qiyang (Colin) Li',
  'Billy Yang',
  'Kaushik',
  'Dimitar I. Dimitrov',
  'Karla Felix Navarro',
  'Kartheek Penagamuri',
  'Hope',
  'Nick Jiang',
  'Shubham Parashar',
  'Arun Sharma',
  'Patricia Doss',
  'Jungtaek Kim',
  'Varun Joshi',
  'Andrei Margeloiu',
  'Varad pimpalkhute',
  'Emaad Manzoor',
  'Amanda Stewart',
  'Subhojyoti Mukherjee',
  'Pei Liu',
  'Shubhashis Roy Dipta',
  'Zhao Dong',
  'Sasikanth',
  'Hongjin Qian',
  'shubo lin',
  'Mingfei Lu',
  'JiamengHuang',
  'Kevin Bleakley',
  'Soham Mehta',
  'Tianyu Liu',
  'Joewie J. Koh',
  'Srijit Seal',
  'Xingyu Qu',
  'Joanne H.',
  'Jizhou Guo',
  '彭晋',
  'Mert Inan',
  'Weicai Yan',
  'Jianzhi Liu',
  'Meirui Jiang',
  'Jingyang Ke',
  'Midsummra',
  'Peisong',
  'Yan Jin',
  'Yufan Zhang',
]
